repos:
  # TODO: correct the repo and rev
  - repo: https://github.com/bryant-finney/pipenv-setup.git
    rev: 3451745992e8e60557578d0ade57e94c5d7586d1
    hooks:
      - id: pipenv-setup
        additional_dependencies: [".[black]"]
        args: [--dev, --pipfile]
